# Generated by Django 2.0.5 on 2018-06-14 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicsite', '0002_facebook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebook',
            options={'verbose_name_plural': 'Facebook'},
        ),
    ]
