# Generated by Django 2.0.5 on 2018-06-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicsite', '0003_auto_20180614_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
